2022-01-19 15:45:07,452 - INFO basePage.py [line:88]: 查找"输入账号"元素，元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[2]/div/div/input")
2022-01-19 15:45:07,452 - INFO basePage.py [line:88]: 查找"输入账号"元素，元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[2]/div/div/input")
2022-01-19 15:45:07,492 - INFO basePage.py [line:113]: 在"输入账号"输入"oms1212",元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[2]/div/div/input")
2022-01-19 15:45:07,492 - INFO basePage.py [line:113]: 在"输入账号"输入"oms1212",元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[2]/div/div/input")
2022-01-19 15:45:07,643 - INFO basePage.py [line:88]: 查找"输入密码"元素，元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[3]/div/div/input")
2022-01-19 15:45:07,643 - INFO basePage.py [line:88]: 查找"输入密码"元素，元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[3]/div/div/input")
2022-01-19 15:45:07,671 - INFO basePage.py [line:113]: 在"输入密码"输入"Qq123456",元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[3]/div/div/input")
2022-01-19 15:45:07,671 - INFO basePage.py [line:113]: 在"输入密码"输入"Qq123456",元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/div[3]/div/div/input")
2022-01-19 15:45:07,869 - INFO basePage.py [line:88]: 查找"点击登录"元素，元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/button")
2022-01-19 15:45:07,869 - INFO basePage.py [line:88]: 查找"点击登录"元素，元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/button")
2022-01-19 15:45:07,895 - INFO basePage.py [line:140]: 点击"点击登录",元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/button")
2022-01-19 15:45:07,895 - INFO basePage.py [line:140]: 点击"点击登录",元素定位:('xpath', "//*[@id='app']/div/div[1]/div[2]/form/button")
2022-01-19 15:45:10,002 - INFO basePage.py [line:88]: 查找"展开模块"元素，元素定位:('class name', 'hamburger-container')
2022-01-19 15:45:10,002 - INFO basePage.py [line:88]: 查找"展开模块"元素，元素定位:('class name', 'hamburger-container')
2022-01-19 15:45:10,034 - INFO basePage.py [line:140]: 点击"展开模块",元素定位:('class name', 'hamburger-container')
2022-01-19 15:45:10,034 - INFO basePage.py [line:140]: 点击"展开模块",元素定位:('class name', 'hamburger-container')
2022-01-19 15:45:11,215 - INFO basePage.py [line:88]: 查找"供应链管理"元素，元素定位:('xpath', "//*[@id='app']/div/div[2]/div[2]/div[1]/div/ul/div[2]/li/div")
2022-01-19 15:45:11,215 - INFO basePage.py [line:88]: 查找"供应链管理"元素，元素定位:('xpath', "//*[@id='app']/div/div[2]/div[2]/div[1]/div/ul/div[2]/li/div")
2022-01-19 15:45:14,210 - INFO basePage.py [line:140]: 点击"供应链管理",元素定位:('xpath', "//*[@id='app']/div/div[2]/div[2]/div[1]/div/ul/div[2]/li/div")
2022-01-19 15:45:14,210 - INFO basePage.py [line:140]: 点击"供应链管理",元素定位:('xpath', "//*[@id='app']/div/div[2]/div[2]/div[1]/div/ul/div[2]/li/div")
2022-01-19 15:45:14,211 - ERROR basePage.py [line:144]: "供应链管理"点击失败
Traceback (most recent call last):
  File "..\Common\basePage.py", line 142, in click_element
    ele.click()
AttributeError: 'NoneType' object has no attribute 'click'
2022-01-19 15:45:14,211 - ERROR basePage.py [line:144]: "供应链管理"点击失败
Traceback (most recent call last):
  File "..\Common\basePage.py", line 142, in click_element
    ele.click()
AttributeError: 'NoneType' object has no attribute 'click'
2022-01-19 15:45:14,217 - ERROR basePage.py [line:249]: 截屏失败!
Traceback (most recent call last):
  File "..\Common\basePage.py", line 142, in click_element
    ele.click()
AttributeError: 'NoneType' object has no attribute 'click'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\Common\basePage.py", line 246, in save_webImgs
    self.driver.save_screenshot(filePath)
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=97.0.4692.71)

2022-01-19 15:45:14,217 - ERROR basePage.py [line:249]: 截屏失败!
Traceback (most recent call last):
  File "..\Common\basePage.py", line 142, in click_element
    ele.click()
AttributeError: 'NoneType' object has no attribute 'click'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\Common\basePage.py", line 246, in save_webImgs
    self.driver.save_screenshot(filePath)
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\bonjour\appdata\local\programs\python\python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=97.0.4692.71)

